socket:
  hostname: localhost
  settings_port: 20201
  data_port: 20202
  data_packet_length: 240 # bytes
  command_packet_length: 8 # bytes

radio:
  baud: 115200
  port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  serial_timeout: 0.1 # seconds

debug:
  fake_radio_connection: false

logging:
  log_to_console: true
  console_format: '%(levelname)s %(message)s'
  file_format: '%(asctime)s %(levelname)s %(message)s'
  file_path: log