socket:
  hostname: localhost
  settings_port: 20201
  data_port: 20202

radio:
  baud: 115200
  port: '/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0'
  serial_timeout: 0.1 # seconds
